Generators:
  0:
    Inventory-Name: "&cGenerator I"
    Name: "Tier I"
    Block: NOTE_BLOCK
    Seconds: 10
    Max: 50
    Items:
    - STONE;5
    - GRASS;4
  1:
    Inventory-Name: "&cGenerator II"
    Name: "Tier II"
    Block: NOTE_BLOCK
    Seconds: 5
    Max: 100
    Items:
    - STONE;9
    - GRASS;8
Messages:
  Warp-Cancelled: "&8You jumped off your ship and fell back to the start."
  Warp-Airspace-Full: "&8Your ship is currently warming up, try again later."
  Warp-Teleportation-Commencing: "&8Teleportation commencing, your ship is being prepared."
  Launching-To: "&8You are being launched to &6&l%landing-pad%&8. &cDo &4&lNOT &cquit until you reach your destination."
  Arrived-At: "&8You have arrived at &6&l%landing-pad%&8."
  Landing-Pad-Does-Not-Exist: "&8The landing pad, &c&l%landing-pad%&8, does not exist."
  Launch-Disabled-World: "&8You can not launch in this world."
  No-Permission: "&cYou do not have permission for that command."
  Incorrect-Syntax: "&cYou used incorrect command syntax."